services:
  writefreely:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - USER=username
      - PASSWORD=password
    volumes:
      - ./config:/config:Z
      - ./data:/data:Z
