services:
  writefreely:
    build:
      context: .
      args:
        - REPOSITORY=$REPOSITORY
        - VERSION=$VERSION
    restart: unless-stopped
    ports:
      - $PORT:8080
    environment:
      - USERNAME
      - PASSWORD
    volumes:
      - ./config:/config:Z
      - ./data:/data:Z
