apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: writefreely
  name: writefreely-custom-cfgmap
data:
  config.ini: |
    [server]
    hidden_host          =
    port                 = 8080
    bind                 = 0.0.0.0
    tls_cert_path        =
    tls_key_path         =
    autocert             = false
    templates_parent_dir = /data  
    static_parent_dir    =
    pages_parent_dir     = /data
    keys_parent_dir      = /data
    hash_seed            =
    gopher_port          = 0

    [database]
    type     = sqlite3
    filename = /data/writefreely.db
    username =
    password =
    database =
    host     = localhost
    port     = 3306
    tls      = false

    [app]
    site_name             = WriteFreely
    site_description      = writing freely
    host                  = https://blog.example.com
    theme                 = write
    editor                =
    disable_js            = false
    webfonts              = true
    landing               =
    simple_nav            = true
    wf_modesty            = true
    chorus                = false
    forest                = false
    disable_drafts        = false
    single_user           = true
    open_registration     = false
    open_deletion         = false
    min_username_len      = 3
    max_blogs             = 1
    federation            = true
    public_stats          = false
    monetization          = false
    notes_only            = false
    private               = false
    local_timeline        = true
    user_invites          =
    default_visibility    =
    update_checks         = false
    disable_password_auth = false
